// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  accordion_block: dynamic(() => import("./AccordionBlock")),
  cta_banner: dynamic(() => import("./CtaBanner")),
  embed_block: dynamic(() => import("./EmbedBlock")),
  full_width_image_section: dynamic(() => import("./FullWidthImageSection")),
  hero_image: dynamic(() => import("./HeroImage")),
  hero_text: dynamic(() => import("./HeroText")),
  hero_video: dynamic(() => import("./HeroVideo")),
  highlight_banner: dynamic(() => import("./HighlightBanner")),
  image_block: dynamic(() => import("./ImageBlock")),
  image_with_text_section: dynamic(() => import("./ImageWithTextSection")),
  letsee: dynamic(() => import("./Letsee")),
  our_team_section: dynamic(() => import("./OurTeamSection")),
  powered_by_research_section: dynamic(
    () => import("./PoweredByResearchSection"),
  ),
  rich_text_block: dynamic(() => import("./RichTextBlock")),
  rich_text_section: dynamic(() => import("./RichTextSection")),
  steps_section: dynamic(() => import("./StepsSection")),
  thanks_to_institutions_section: dynamic(
    () => import("./ThanksToInstitutionsSection"),
  ),
  video_block: dynamic(() => import("./VideoBlock")),
};
